apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-appset-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/theadityab/app-of-apps.git
    path: argcd-appset  # Now pointing only to the ApplicationSet manifest directory
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc  # Points to the centralized Argo CD instance
    namespace: argocd  # Ensures the ApplicationSet is deployed in the argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
