apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: adi-applicaitonset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        targetversion : release-1.1
      - namespace: qa
        targetversion : release-1.1
      - namespace: stage
        targetversion : release-1.1
  template:
    metadata:
      name: '{{namespace}}-core-app'
    spec:
      destination:
        namespace: myapp
        server: https://kubernetes.default.svc
      project: bu-test
      source:
        helm:
          valueFiles:
          - values-{{namespace}}.yaml
        path: argo-helm
        repoURL: https://github.com/theadityab/argo-testing.git
        targetRevision: {{targetversion}}
      syncPolicy:
        automated: null
        syncOptions:
          - CreateNamespace=true
