apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  selector:
    matchLabels:
      app: core
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: myapp
        image: adityab01/sampleapp:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myregistrykey